Debugging SSH error

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -41,8 +41,8 @@ jobs:
           password: ${{ secrets.DOCKER_PASSWORD }}
       - name: Build and push Docker image
         run: |
-          docker build -t ${{ secrets.DOCKER_USERNAME }}/com619-devops-devops:latest .
-          docker push ${{ secrets.DOCKER_USERNAME }}/com619-devops-devops:latest
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops_com619-devops:latest .
+          docker push ${{ secrets.DOCKER_USERNAME }}/devops_com619-devops:latest
           
   deploy:
     needs: publish_to_docker
@@ -54,8 +54,11 @@ jobs:
         run: |
           mkdir -p ~/.ssh
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+          if [ $? -ne 0 ]; then echo "Writing key failed"; exit 1; fi
           chmod 600 ~/.ssh/id_rsa
+          if [ $? -ne 0 ]; then echo "Chmod failed"; exit 1; fi
           ssh-keyscan -H com619trial.uksouth.cloudapp.azure.com >> ~/.ssh/known_hosts
+          if [ $? -ne 0 ]; then echo "Ssh-keyscan failed"; exit 1; fi
 
       - name: Check SSH Key Line Count
         run: wc -l ~/.ssh/id_rsa
